defaults:
  - gi_tract_seg.yaml
net:
  _target_: segmentation_models_pytorch.DeepLabV3Plus
  encoder_name: timm-resnest50d
  in_channels: 1
  classes: 3
criterion:
  _target_: gi_tract_seg.models.losses.joint_loss.JointLoss
  first:
    _target_: segmentation_models_pytorch.losses.DiceLoss
    mode: multilabel
  second:
    _target_: segmentation_models_pytorch.losses.SoftBCEWithLogitsLoss
  third:
    _target_: segmentation_models_pytorch.losses.LovaszLoss
    mode: multilabel
  weight_first: 0.8
  weight_second: 0.1
  weight_third: 0.1
lr_scheduler_name: ReduceLROnPlateau
lr_scheduler_params:
  - factor: 0.5
  - patience: 10
optimizer_name: AdamP
optimizer_params:
  - lr: 0.00005
  - weight_decay: 0.0001
