_target_: gi_tract_seg.models.module.GITractSegmentatonLitModule
optimizer_name: AdamP
optimizer_params:
  - lr: 0.0005
  - weight_decay: 0.0001
lr_scheduler_name: ReduceLROnPlateau
lr_scheduler_params:
  - factor: 0.5
  - patience: 10
lr_scheduler_monitor: 'val/loss'
net:
  _target_: segmentation_models_pytorch.unet.Unet
  encoder_name: resnet18
  in_channels: 1
  classes: 3
  encoder_weights: "imagenet"
criterion:
  _target_: gi_tract_seg.models.losses.joint_loss.JointLoss
  first:
    _target_: segmentation_models_pytorch.losses.TverskyLoss
    mode: multilabel
  second:
    _target_: segmentation_models_pytorch.losses.SoftBCEWithLogitsLoss
  weight_first: 0.8
  weight_second: 0.2
