_target_: gi_tract_seg.data.datamodule.GITractDataModule
data_path: ${work_dir}/data/processed/train_df_agg_cleaned.parquet
images_path: ${work_dir}/data/raw/train/
masks_path: ${work_dir}/data/processed/masks/
val_fold: 0
batch_size: 8
num_workers: 6
pin_memory: True
train_augmentations:
  _target_: gi_tract_seg.models.augmentations.transforms.default_valid_transform
  resize_size: 256
val_augmentations:
  _target_: gi_tract_seg.models.augmentations.transforms.default_valid_transform
  resize_size: 256
shuffle_train: True
keep_non_empty: False
apply_filters: False
use_pseudo_3d: False
channels: -1
stride: -1
