defaults:
  - gi_tract.yaml
train_augmentations:
  _target_: gi_tract_seg.models.augmentations.transforms.kaggle_training_transforms
  resize_size: 256
val_augmentations:
  _target_: gi_tract_seg.models.augmentations.transforms.kaggle_training_transforms
  resize_size: 256
