defaults:
  - gi_tract.yaml
train_augmentations:
  _target_: gi_tract_seg.models.augmentations.transforms.medium_training_transforms
  resize_size: 256
val_augmentations:
  _target_: gi_tract_seg.models.augmentations.transforms.default_valid_transform
  resize_size: 256
