defaults:
  - gi_tract.yaml
train_augmentations:
  _target_: gi_tract_seg.models.augmentations.transforms.medium_training_transforms
  size: [320, 384]
  padding: True
val_augmentations:
  _target_: gi_tract_seg.models.augmentations.transforms.default_valid_transform
  size: [320, 384]
  padding: True
